name: Generate Subscription File

on:
  push:
    branches:
      - main
  schedule:
    # 每6小时运行一次
    - cron: '0 */6 * * *'
  workflow_dispatch: # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # ----- 这里是修改的部分 -----
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 lxml
      # ----- 修改结束 -----
      
      - name: Run script to generate subscription
        run: python generate_sub.py

      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: Auto-update subscription file"
          file_pattern: sub.txt # 只提交 'sub.txt' 这个文件的变动
          commit_options: '--no-verify'
          # 可选：让提交者显示为GitHub Actions机器人
          commit_user_name: "github-actions[bot]"
          commit_user_email: "41898282+github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
