name: Generate Subscription File

on:
  push:
    branches:
      - main
  schedule:
    # 每6小时运行一次
    - cron: '0 */6 * * *'
  workflow_dispatch: # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run script to generate subscription
        run: python generate_sub.py

      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: Auto-update subscription file"
          file_pattern: sub # 只提交 'sub' 这个文件的变动
          commit_options: '--no-verify'
          # 可选：如果你想让提交者显示为GitHub Actions机器人
          commit_user_name: "github-actions[bot]"
          commit_user_email: "41898282+github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
