name: Generate Subscription File

on:
  push:
    branches:
      - main
  schedule:
    # 每6小时运行一次 (UTC时间)
    - cron: '0 */6 * * *'
  workflow_dispatch: # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run script to generate subscription
        run: python generate_sub.py # 将要创建的Python脚本

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output # 我们将把生成的文件放在output目录
          cname: '' # 如果你有自定义域名可以填写，否则留空
